Repository rdkcentral/ut-core, pull requests merged in 2024-05, with the labels that each got.

#29 Feature/gh13 key value pair profile input
  .gitignore
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  Makefile
  NOTICE
  build.sh
  include/ut_kvp.h
  include/ut_kvp_assert.h
  src/cunit/cunit_lgpl/ut_automated.c
  src/cunit/cunit_lgpl/ut_basic.c
  src/cunit/cunit_lgpl/ut_console.c
  src/libyaml/patches/CorrectWarningsAndBuildIssuesInLibYaml.patch
  src/ut_kvp.c
  src/ut_kvp_assert.c
  src/ut_main.c
  tests/Makefile
  tests/src/assets/no_data_file.yaml
  tests/src/assets/test_kvp.json
  tests/src/assets/test_kvp.yaml
  tests/src/assets/zero_length.yaml
  tests/src/ut_test_assert.c
  tests/src/ut_test_kvp.c
  tests/src/ut_test_kvp_assert.c
  tests/src/ut_test_main.c
  ut-core-dev.code-workspace
Labels: enhancement

#36 Gh24 - Input configuration switch
  .vscode/launch.json
  include/ut_kvp_assert.h
  include/ut_main.h
  src/cunit/ut_cunit.c
  src/ut_kvp.c
  src/ut_main.c
  tests/src/ut_test_kvp.c
  tests/src/ut_test_main.c
  ut-core-dev.code-workspace
Labels: enhancement

#47 gh#46 corrected bug in the build script
  build.sh
Labels: bug

#57 Updating HLTS & LLTS templates
  docs/pages/High-Level_Testpecification_template.md
  docs/pages/Low-Level_TestSpecification_example.md
  docs/pages/Low-Level_TestSpecification_template.md
  docs/pages/l2_module_test_specification_example.md
Labels: documentation
